<a href="https://colab.research.google.com/github/paulbruffett/python_class/blob/master/A01_Python_Refresher.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Python Refresher
This notebook covers some of the key programming concepts in Python

###Let's start with some basic operations and data types:

In [50]:
1+1

2

In [51]:
5/3

1.6666666666666667

In [0]:
#variables are dynamically typed, this is great and terrible
number = 5

In [53]:
number+3

8

In [54]:
number+3.5

8.5

In [55]:
number+'abc'

TypeError: ignored

In [0]:
#I can overwrite without re-typing or initializing
number = 'abc'

In [57]:
#operators work in a variety of ways on a variety of things
number + 'defg'

'abcdefg'

### Objects: lists and dictionaries
Lists are ordered sets of (possibly) heterogeneous things, could be numbers, strings, other lists, functions or objects...

Dictionaries are key/value pairs and can contain a variety of objects as the values, usually a key is a word or number.

In [0]:
a_list = [1,2,3,4]

In [59]:
a_list

[1, 2, 3, 4]

In [60]:
#we access using brackets and the number position of the object
a_list[0]

1

In [61]:
a_list[-1]

4

In [62]:
#we can slice a list to access one or many objects from it
a_list[:2]

[1, 2]

In [0]:
#appending can be done using a method on the list object
a_list.append(5)

In [64]:
a_list

[1, 2, 3, 4, 5]

In [0]:
a_list.append([10,11,12])

In [66]:
a_list

[1, 2, 3, 4, 5, [10, 11, 12]]

In [67]:
#I can index into an arbitrary number of lists or objects inside a list!
a_list[-1][0]

10

In [0]:
a_dictionary = {'USA':"Washington","Mexico":"Mexico City","Peru":"Lima"}

In [69]:
#position is irrelevant in a dictionary, instead you access the value using the key
a_dictionary['USA']

'Washington'

In [0]:
#appending also doesn't make sense, we add in key value pairs, if a key doesn't already exist it's added
a_dictionary['Canada'] = 'Ottawa'

In [71]:
a_dictionary

{'Canada': 'Ottawa',
 'Mexico': 'Mexico City',
 'Peru': 'Lima',
 'USA': 'Washington'}

In [0]:
a_dictionary['list'] = [1,2,3,4]

In [73]:
a_dictionary

{'Canada': 'Ottawa',
 'Mexico': 'Mexico City',
 'Peru': 'Lima',
 'USA': 'Washington',
 'list': [1, 2, 3, 4]}

In [74]:
#indexing in a list in a dictionary
a_dictionary['list'][0]

1

### Iterators and Conditionals
We can use for loops to iterate over a list or dictionary or object that supports iteration.  You'll notice the indent, indentation is required in Python and denotes relationships, in this case all indented code is contained in the for loop.

In [75]:
for i in [1,2,3]:
  print(i)

1
2
3


In [0]:
#i is just a variable, it could be called anything and has no impact on the source iterator or list
num_list = [1,2,3,4,5,6]
for i in num_list:
  i+1

In [77]:
#if I wanted to take the num_list and add one to each number I could do this:
for i in range(len(num_list)):
  print(i)
  num_list[i]+=1

num_list

0
1
2
3
4
5


[2, 3, 4, 5, 6, 7]

Range + len gives me an iterator from 0 through the length of the item, in this case the list.  It's a good way to loop through by indexing.

In [78]:
#while continues until the statement evaulates to FALSE
c = 0
while c<5:
  print('still going, c is %d' %c)
  c+=1

still going, c is 0
still going, c is 1
still going, c is 2
still going, c is 3
still going, c is 4


In [79]:
if 5>3:
  print('5 is bigger')

5 is bigger


In [81]:
#will stop looping when the if statement evaluates to True, break exits the containing loop.
c = 0
while True:
  print(c)
  c+=1
  if c>6:
    break

0
1
2
3
4
5
6


### Functions and classes
Functions allow us to make reusable bits of code, classes allow us to make objects that are extensible.

In [0]:
def exp_func(num):
  return num**2

In [84]:
exp_func(5)

25

In [0]:
def exp_func(num,pow):
  return num**pow

In [86]:
exp_func(5,3)

125

In [87]:
exp_func(5,2)

25

In [0]:
class Numbers:
  def __init__(self, num, exp):
    self.n = num
    self.e = exp
  
  def raise_exp(self):
    return self.n**self.e

x = Numbers(2, 5)

In [113]:
x.n

2

In [114]:
x.e

5

In [115]:
x.raise_exp()

32

In [0]:
y = Numbers(3,5)

In [117]:
y.raise_exp()

243

### Importing libraries
Libraries are prebuilt functions and modules.  The huge number of available libraries makes Python very powerful and flexible, you can find libraries for statistical processing, machine learning and industry use cases.

In [0]:
import numpy as np

In [0]:
#an array is the core data construct in numpy, which is the dominant statistics library in Python
x = np.array([1,3,5,7,9])

In [122]:
x

array([1, 3, 5, 7, 9])

In [124]:
x.mean()

5.0

In [125]:
x.max()

9

In [127]:
# NP arrays behave quite a lot like lists in Python
x[-1]

9

In [128]:
#except not completely
x+1

array([ 2,  4,  6,  8, 10])

In [0]:
x_m = np.array([[3,5,7,11,20],[12,20,55,23,99]])

In [134]:
#we can easily represent matrices and vectors
x_m

array([[ 3,  5,  7, 11, 20],
       [12, 20, 55, 23, 99]])

In [135]:
#and do matrix addition, or multiplication 
x_m+x

array([[  4,   8,  12,  18,  29],
       [ 13,  23,  60,  30, 108]])

In [137]:
x_m.dot(x)

array([ 310, 1399])

In [138]:
x_m[0][0]

3